Revamp: global style
dunglas/calavera-react-client pull request #28
Opened 2016-10-25 23:04 UTC by Gregcop1

![screencapture-localhost-3000-1477436595410](https://cloud.githubusercontent.com/assets/1257968/19707488/242a05b6-9b18-11e6-92c4-2fb50994b82f.png)

2016-10-26 06:03 UTC, dunglas requested changes

2016-10-26 06:03 UTC, dunglas commented on src/containers/Home/Home.js
> +            <Link className="btn btn-primary btn-lg" to="https://demo.api-platform.com" role="button"><span className="fa fa-mouse-pointer"/>Demo</Link>
Should be `<a>` tag because it's an external URL.

2016-10-26 06:03 UTC, dunglas commented on src/containers/Home/Home.js
> +            <h2>Creating Linked Data <a href="https://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">REST</a> APIs has never been so easy</h2>
Shouldn't it a `<h1>` tag (first title element of a `<section>`, IIRC the `<section>` element reset the titling level.

2016-10-26 06:03 UTC, dunglas commented on src/containers/Home/Home.js
> +            <h2>The web has changed!</h2>
Same here, why changing to a `<h2>`?

2016-10-26 06:03 UTC, dunglas commented on src/containers/Home/Home.js
> +                <h3>Javascript webapps (<a href="https://en.wikipedia.org/wiki/Single-page_application" target="_blank">SPA</a>) are the standard.</h3>
Are those sections titles?

2016-10-26 06:03 UTC, dunglas commented on src/containers/Navigation/HeaderNav.js
> +              <Link className="navbar-brand" to="/"><img height="48" src={logoImage} alt="API Platform" /></Link>
`height={48}`?

2016-10-26 06:03 UTC, dunglas commented on src/containers/Navigation/HeaderNav.js
> +              <NavItem eventKey={1} href="https://api.github.com/repos/api-platform/api-platform/zipball" target="_blank"><span className="fa fa-download" /> Download</NavItem>
It should link to the download page and not directly to the ZIP.

2016-10-26 06:03 UTC, dunglas commented on src/theme/bootstrap.overrides.scss
> +.incredible {
If we don't use them in CSS, maybe should we remove ids from the HTML too.

2016-10-26 06:04 UTC, dunglas commented
The new design is pretty! Thanks!!

I left some minor comments but it will be a great improvement to the website.

2016-10-26 06:21 UTC, dunglas commented
Got it for the download link, the page has been removed. It makes sense.

There is a bug in the doc: the title is hided:

<img width="1440" alt="capture d ecran 2016-10-26 a 08 16 38" src="https://cloud.githubusercontent.com/assets/57224/19715306/8ead3778-9b54-11e6-91c8-a96a778fde82.png">

Also, links to anchors doesn't work (they send to the top of the page), but I think that this bug was already present before your PR.

There are also 2 new problems with Algolia. When the navbar is in the bottom, the search results are hided because they are displayed under the bar (not sure if there is an easy way to fix this).

<img width="987" alt="capture d ecran 2016-10-26 a 08 19 10" src="https://cloud.githubusercontent.com/assets/57224/19715372/0441209e-9b55-11e6-8231-6432ab8ad48c.png">

Another new bug: when you go to the homepage then go to another page, Algolia doesn't work (it is working fine on the current version).

2016-10-26 06:31 UTC, dunglas commented
It is possible to customize where to display Algolia's result, for instance it's what Batch is doing: https://batch.com/doc

2016-10-26 06:52 UTC, Gregcop1 commented on src/containers/Navigation/HeaderNav.js
> +              <Link className="navbar-brand" to="/"><img height="48" src={logoImage} alt="API Platform" /></Link>
why ?

2016-10-26 06:52 UTC, Gregcop1 commented on src/containers/Home/Home.js
> +            <Link className="btn btn-primary btn-lg" to="https://demo.api-platform.com" role="button"><span className="fa fa-mouse-pointer"/>Demo</Link>
Yep, bad conflict's resolve

2016-10-26 07:00 UTC, Gregcop1 commented on src/containers/Home/Home.js
> +            <h2>Creating Linked Data <a href="https://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">REST</a> APIs has never been so easy</h2>
There's a huge debate about that: having one h1 or multiple h1.
In term of SEO and accessibility, having a clear hierarchy is way better. The main info of your website is the title "API Platform" .
In term of accessibility, they can navigate inside of a page through a special menu built by heading level (and I don't think there's a reset on section for it)
The actual code doesn't built hierarchy at all. All infos are on the same level and I think we have to change this

2016-10-26 07:04 UTC, Gregcop1 commented on src/containers/Navigation/HeaderNav.js
> +              <NavItem eventKey={1} href="https://api.github.com/repos/api-platform/api-platform/zipball" target="_blank"><span className="fa fa-download" /> Download</NavItem>
I discuss that with @K-mos and this download page with two links is reaaalllly empty :)
IMHO, we should remove it until we have something to say in it

2016-10-26 07:06 UTC, dunglas commented on src/containers/Home/Home.js
> +            <h2>Creating Linked Data <a href="https://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">REST</a> APIs has never been so easy</h2>
But we use HTML5, and the HTML5 outline algorithm is part of the spec: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines

IMO it's a urban legend that using the old way is better for SEO, and I generally prefer to respect the standard, but let's do this if you find that it's better.

2016-10-26 07:06 UTC, Gregcop1 commented on src/theme/bootstrap.overrides.scss
> +.incredible {
Forget it... we can remove the whole CSS :) 
I don't know if you use those ids somewhere in JS but I can remove them if you want. But this PR shouldn't contain the whole revamp IMO cause there's really a lot of things to do to clean this mess

2016-10-26 07:07 UTC, dunglas commented on src/containers/Navigation/HeaderNav.js
> +              <Link className="navbar-brand" to="/"><img height="48" src={logoImage} alt="API Platform" /></Link>
Because it's an int?

2016-10-26 07:07 UTC, dunglas commented on src/containers/Navigation/HeaderNav.js
> +              <Link className="navbar-brand" to="/"><img height="48" src={logoImage} alt="API Platform" /></Link>
And for consistency (`eventKey={1}` for instance).

2016-10-26 07:08 UTC, Gregcop1 commented
Ok, I will check this for Algolia
At worst, I will tinker something in CSS

2016-10-26 11:47 UTC, Gregcop1 commented on src/containers/Home/Home.js
> +            <h2>Creating Linked Data <a href="https://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank">REST</a> APIs has never been so easy</h2>
For SEO maybe but not for screen readers ;) And it's not out of the standard. The new standard don't remove the old way of writing structured heading

2016-10-26 11:50 UTC, Gregcop1 commented on src/containers/Home/Home.js
> +                <h3>Javascript webapps (<a href="https://en.wikipedia.org/wiki/Single-page_application" target="_blank">SPA</a>) are the standard.</h3>
It's about structuring content importance. IMHO it's more important than a basic paragraph but I may be wrong

2016-10-26 22:23 UTC, Gregcop1 commented
I've just fix:

- [X] Algolia integration when the side is not fixed to top
- [X] Aloglia init script is now refresh each time a new header is build

2016-10-27 05:53 UTC, merged

2016-10-27 05:54 UTC, dunglas commented
Thank you very much @Gregcop1